### ISSUE TITLE
Nvm alias default not sticking

### ISSUE THREAD

**Issue by externl** [passcod/nvm-fish-wrapper#5]
```
$ nvm current
system
$ nvm alias default stable
stable
default -> stable (-> v0.12.0)
```

restart shell

```
$ source ~/.nvm-fish-wrapper/nvm.fish
$ nvm current
system
```

Not sure if it's a bug for my env is weird.

OS 10.10
Fish 2.1.1

**Comment by passcod** [comment]
Firstly, are you using the latest version of nvm-wrapper?
Secondly, a quick workaround is to run `nvm use default` straight after sourcing it.

I think what the issue is is that nvm might set the default in bash, but I don't copy the env across during the initial sourcing. I'll have to think about whether this is desired behaviour and research to see if it's feasible.

**Comment by externl** [comment]
Yep, latest version (51c9a8e559e5716c66186cba006eced857c4cbfa).

According to https://github.com/creationix/nvm, alias default is "To set a default Node version to be used in any new shell". Seems to me like the env should be copied after sourcing.
